/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rafaelfdequeiroz' at '01/07/17 10:19' with Gradle 2.4
 *
 * @author rafaelfdequeiroz, @date 01/07/17 10:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
